export const MASSNAHMEN = {
  ERGO: [
    'Motorisch-funktionelle Behandlung',
    'Sensomotorisch-perzeptive Behandlung',
    'Hirnleistungstraining',
    'Psychisch-funktionelle Behandlung',
    'Thermische Anwendung',
    'Beratung zur Alltagsintegration',
    'Schienenherstellung/-anpassung',
    'Gruppentherapie',
    'Hausbesuch',
    'Verlaufsdokumentation',
  ],
  PHYSIO: [
    'Krankengymnastik (KG)',
    'KG-ZNS Erwachsene (Bobath/Vojta/PNF)',
    'KG-ZNS Kinder',
    'KG-Atemtherapie',
    'KG am Gerät (KGG)',
    'Manuelle Therapie (MT)',
    'Klassische Massagetherapie',
    'Bindegewebsmassage',
    'Periostmassage',
    'Kolonbehandlung',
    'Manuelle Lymphdrainage 30 Min',
    'Manuelle Lymphdrainage 45 Min',
    'Manuelle Lymphdrainage 60 Min',
    'Wärmetherapie (Heiße Rolle/Fango)',
    'Kältetherapie',
    'Elektrotherapie',
    'Elektrostimulation',
    'Iontophorese',
    'Ultraschall-Wärmetherapie',
    'Hydroelektrisches Vollbad',
    'Bewegungsbad/Wassergymnastik',
    'Inhalation',
    'Hausbesuch',
  ],
  LOGO: [
    'Sprachtherapie 30 Min',
    'Sprachtherapie 45 Min',
    'Sprachtherapie 60 Min',
    'Sprechtherapie 30 Min',
    'Sprechtherapie 45 Min',
    'Sprechtherapie 60 Min',
    'Stimmtherapie 30 Min',
    'Stimmtherapie 45 Min',
    'Stimmtherapie 60 Min',
    'Schlucktherapie 30 Min',
    'Schlucktherapie 45 Min',
    'Schlucktherapie 60 Min',
    'Standardisierter Eingangsbefund',
    'Therapiebericht',
    'Beratung Eltern/Bezugspersonen',
    'Beratung Schluckstörung',
    'Gruppentherapie',
    'Hausbesuch',
  ],
};

export const ZUSATZ_OPTIONEN = [
  '',
  'als Hausbesuch',
  'als Doppelbehandlung',
  'in der Gruppe',
  'mit Wärmetherapie',
  'mit Kältetherapie',
];

export const DEFAULTS = {
  offsetX: 12,
  offsetY: 55,
  zeilenhoehe: 7,
  schriftgroesse: 9,
  schriftart: 'Arial',
};
